<a href="https://colab.research.google.com/github/tettehdaniel/my-vis-5609/blob/main/Notebooks/Notebook03_DataManipulation1_SV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook 03 — Data Manipulation One

**Main Objective**

1. Sorting
2. Selecting
3. Filtering

## Setup

Please run the setup code below

In [1]:
! wget -q -nc https://raw.githubusercontent.com/taylor-arnold/fds-py/refs/heads/main/funs.py

from funs import *

In [2]:
import numpy as np
import polars as pl

from plotnine import *
from polars import col as c
theme_set(theme_minimal())

path = "https://raw.githubusercontent.com/ajcollins16/DSST289_Fall2026_AJC/refs/heads/main/"

In [3]:
dat = pl.read_csv(path + "Data/food.csv").drop(c.description)

In [4]:
dat.head()

shape: (5, 16)
┌───────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ item      ┆ food_group ┆ calories ┆ total_fat ┆ … ┆ vitamin_a ┆ vitamin_c ┆ wiki      ┆ color  │
│ ---       ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---    │
│ str       ┆ str        ┆ i64      ┆ f64       ┆   ┆ i64       ┆ i64       ┆ str       ┆ str    │
╞═══════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ Apple     ┆ fruit      ┆ 52       ┆ 0.1       ┆ … ┆ 1         ┆ 8         ┆ apple     ┆ red    │
│ Asparagus ┆ vegetable  ┆ 20       ┆ 0.1       ┆ … ┆ 15        ┆ 9         ┆ asparagus ┆ green  │
│ Avocado   ┆ fruit      ┆ 160      ┆ 14.6      ┆ … ┆ 3         ┆ 17        ┆ avocado   ┆ green  │
│ Banana    ┆ fruit      ┆ 89       ┆ 0.3       ┆ … ┆ 1         ┆ 15        ┆ banana    ┆ yellow │
│ Chickpea  ┆ grains     ┆ 180      ┆ 2.9       ┆ … ┆ 0         ┆ 3         ┆ chickpea  ┆ brown  │
└───────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

## Sorting, Selecting, and Filtering

Although simple in concept, the ability to sort, select, and filter data is one of the first steps to cleaning messy data. Simply put:
- Sorting &rarr; reordering data to inspect certain things.
- Selecting &rarr; picking the variables that are most important for what you want to accomplish.
- Filtering &rarr; removing observations based on a set of condition(s).

We are going to work through a number of data manipulation exercises today. Although simple, starting small is the best path forward for more complex data manipulations. The data we will be working with continues to be the food dataset we have been working with.

### Questions

1. Start by sorting the food data by calories, with the lowest caloric foods at the top (display only).

In [5]:
(
    dat
    .sort(c.calories)
)

shape: (61, 16)
┌───────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ item      ┆ food_group ┆ calories ┆ total_fat ┆ … ┆ vitamin_a ┆ vitamin_c ┆ wiki      ┆ color  │
│ ---       ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---    │
│ str       ┆ str        ┆ i64      ┆ f64       ┆   ┆ i64       ┆ i64       ┆ str       ┆ str    │
╞═══════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ Cucumber  ┆ vegetable  ┆ 12       ┆ 0.1       ┆ … ┆ 1         ┆ 5         ┆ cucumber  ┆ green  │
│ Celery    ┆ vegetable  ┆ 14       ┆ 0.1       ┆ … ┆ 9         ┆ 5         ┆ celery    ┆ green  │
│ Lettuce   ┆ vegetable  ┆ 14       ┆ 0.1       ┆ … ┆ 10        ┆ 5         ┆ lettuce   ┆ green  │
│ Tomato    ┆ vegetable  ┆ 18       ┆ 0.0       ┆ … ┆ 17        ┆ 21        ┆ tomato    ┆ red    │
│ Asparagus ┆ vegetable  ┆ 20       ┆ 0.1       ┆ … ┆ 15        ┆ 9         ┆ asparagus ┆ green  │
│ …         ┆ …          ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …      │
│ Pork      ┆ meat       ┆ 271      ┆ 17.0      ┆ … ┆ 1         ┆ 1         ┆ pork      ┆ white  │
│ Beef      ┆ meat       ┆ 288      ┆ 19.5      ┆ … ┆ 0         ┆ 0         ┆ beef      ┆ red    │
│ Lamb      ┆ meat       ┆ 292      ┆ 20.7      ┆ … ┆ 0         ┆ 0         ┆ sheep     ┆ red    │
│ Cheese    ┆ dairy      ┆ 350      ┆ 26.9      ┆ … ┆ 16        ┆ 0         ┆ cheese    ┆ yellow │
│ Oat       ┆ grains     ┆ 389      ┆ 6.0       ┆ … ┆ 0         ┆ 0         ┆ oat       ┆ brown  │
└───────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

2. Next, sort the data by calories from highest to lowest (display only).

In [7]:
(
    dat
    .sort(c.calories, descending=True) #argument
)

shape: (61, 16)
┌───────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ item      ┆ food_group ┆ calories ┆ total_fat ┆ … ┆ vitamin_a ┆ vitamin_c ┆ wiki      ┆ color  │
│ ---       ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---    │
│ str       ┆ str        ┆ i64      ┆ f64       ┆   ┆ i64       ┆ i64       ┆ str       ┆ str    │
╞═══════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ Oat       ┆ grains     ┆ 389      ┆ 6.0       ┆ … ┆ 0         ┆ 0         ┆ oat       ┆ brown  │
│ Cheese    ┆ dairy      ┆ 350      ┆ 26.9      ┆ … ┆ 16        ┆ 0         ┆ cheese    ┆ yellow │
│ Lamb      ┆ meat       ┆ 292      ┆ 20.7      ┆ … ┆ 0         ┆ 0         ┆ sheep     ┆ red    │
│ Beef      ┆ meat       ┆ 288      ┆ 19.5      ┆ … ┆ 0         ┆ 0         ┆ beef      ┆ red    │
│ Pork      ┆ meat       ┆ 271      ┆ 17.0      ┆ … ┆ 1         ┆ 1         ┆ pork      ┆ white  │
│ …         ┆ …          ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …      │
│ Asparagus ┆ vegetable  ┆ 20       ┆ 0.1       ┆ … ┆ 15        ┆ 9         ┆ asparagus ┆ green  │
│ Tomato    ┆ vegetable  ┆ 18       ┆ 0.0       ┆ … ┆ 17        ┆ 21        ┆ tomato    ┆ red    │
│ Celery    ┆ vegetable  ┆ 14       ┆ 0.1       ┆ … ┆ 9         ┆ 5         ┆ celery    ┆ green  │
│ Lettuce   ┆ vegetable  ┆ 14       ┆ 0.1       ┆ … ┆ 10        ┆ 5         ┆ lettuce   ┆ green  │
│ Cucumber  ┆ vegetable  ┆ 12       ┆ 0.1       ┆ … ┆ 1         ┆ 5         ┆ cucumber  ┆ green  │
└───────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

3. Now, sort the data based on the food groups (alphabetical order) and then within each food group by calories (display only). *Note: from now on if it says "sort" I am implying ascending order unless otherwise noted.*

In [8]:
(
    dat
    .sort(c.food_group, c.calories)
)

shape: (61, 16)
┌────────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬────────────┬────────┐
│ item       ┆ food_group ┆ calories ┆ total_fat ┆ … ┆ vitamin_a ┆ vitamin_c ┆ wiki       ┆ color  │
│ ---        ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---        ┆ ---    │
│ str        ┆ str        ┆ i64      ┆ f64       ┆   ┆ i64       ┆ i64       ┆ str        ┆ str    │
╞════════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪════════════╪════════╡
│ Milk       ┆ dairy      ┆ 60       ┆ 3.2       ┆ … ┆ 2         ┆ 0         ┆ milk       ┆ white  │
│ Yogurt     ┆ dairy      ┆ 99       ┆ 1.1       ┆ … ┆ 1         ┆ 1         ┆ yogurt     ┆ white  │
│ Sour Cream ┆ dairy      ┆ 214      ┆ 20.9      ┆ … ┆ 13        ┆ 2         ┆ sour_cream ┆ white  │
│ Cheese     ┆ dairy      ┆ 350      ┆ 26.9      ┆ … ┆ 16        ┆ 0         ┆ cheese     ┆ yellow │
│ Crab       ┆ fish       ┆ 87       ┆ 1.0       ┆ … ┆ 0         ┆ 5         ┆ callinecte ┆ red    │
│            ┆            ┆          ┆           ┆   ┆           ┆           ┆ s_sapidus  ┆        │
│ …          ┆ …          ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …          ┆ …      │
│ Carrot     ┆ vegetable  ┆ 41       ┆ 0.2       ┆ … ┆ 336       ┆ 10        ┆ carrot     ┆ orange │
│ Onion      ┆ vegetable  ┆ 42       ┆ 0.0       ┆ … ┆ 0         ┆ 11        ┆ onion      ┆ white  │
│ Corn       ┆ vegetable  ┆ 86       ┆ 1.1       ┆ … ┆ 4         ┆ 11        ┆ maize      ┆ yellow │
│ Sweet      ┆ vegetable  ┆ 86       ┆ 0.0       ┆ … ┆ 284       ┆ 4         ┆ sweet_pota ┆ orange │
│ Potato     ┆            ┆          ┆           ┆   ┆           ┆           ┆ to         ┆        │
│ Potato     ┆ vegetable  ┆ 104      ┆ 2.0       ┆ … ┆ 2         ┆ 12        ┆ potato     ┆ white  │
└────────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴────────────┴────────┘

4. Now, select only the food groups and calories columns of the dataset (display only).

In [9]:
(
    dat
    .select(c.food_group, c.calories)
)

shape: (61, 2)
┌────────────┬──────────┐
│ food_group ┆ calories │
│ ---        ┆ ---      │
│ str        ┆ i64      │
╞════════════╪══════════╡
│ fruit      ┆ 52       │
│ vegetable  ┆ 20       │
│ fruit      ┆ 160      │
│ fruit      ┆ 89       │
│ grains     ┆ 180      │
│ …          ┆ …        │
│ vegetable  ┆ 18       │
│ fish       ┆ 153      │
│ meat       ┆ 187      │
│ vegetable  ┆ 104      │
│ dairy      ┆ 99       │
└────────────┴──────────┘

5. Let's chain several things together. Create a new dataset variable (call it `dat2`) that has the ten items with the largest amount of calories per serving. Make sure you inspect the new dataset to make sure you did the correct manipulation.

In [14]:
dat2 = (
    dat
    .sort(c.calories, descending=True)
    .head(10)
)
dat2

shape: (10, 16)
┌────────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬────────────┬────────┐
│ item       ┆ food_group ┆ calories ┆ total_fat ┆ … ┆ vitamin_a ┆ vitamin_c ┆ wiki       ┆ color  │
│ ---        ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---        ┆ ---    │
│ str        ┆ str        ┆ i64      ┆ f64       ┆   ┆ i64       ┆ i64       ┆ str        ┆ str    │
╞════════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪════════════╪════════╡
│ Oat        ┆ grains     ┆ 389      ┆ 6.0       ┆ … ┆ 0         ┆ 0         ┆ oat        ┆ brown  │
│ Cheese     ┆ dairy      ┆ 350      ┆ 26.9      ┆ … ┆ 16        ┆ 0         ┆ cheese     ┆ yellow │
│ Lamb       ┆ meat       ┆ 292      ┆ 20.7      ┆ … ┆ 0         ┆ 0         ┆ sheep      ┆ red    │
│ Beef       ┆ meat       ┆ 288      ┆ 19.5      ┆ … ┆ 0         ┆ 0         ┆ beef       ┆ red    │
│ Pork       ┆ meat       ┆ 271      ┆ 17.0      ┆ … ┆ 1         ┆ 1         ┆ pork       ┆ white  │
│ Catfish    ┆ fish       ┆ 240      ┆ 14.5      ┆ … ┆ 1         ┆ 1         ┆ catfish    ┆ white  │
│ Halibut    ┆ fish       ┆ 239      ┆ 17.7      ┆ … ┆ 1         ┆ 0         ┆ halibut    ┆ white  │
│ Chicken    ┆ meat       ┆ 237      ┆ 13.4      ┆ … ┆ 3         ┆ 0         ┆ chicken    ┆ white  │
│ Scallop    ┆ fish       ┆ 217      ┆ 10.9      ┆ … ┆ 2         ┆ 4         ┆ scallop    ┆ white  │
│ Sour Cream ┆ dairy      ┆ 214      ┆ 20.9      ┆ … ┆ 13        ┆ 2         ┆ sour_cream ┆ white  │
└────────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴────────────┴────────┘

6. With the new dataset, extract the one row with the lowest amount of protein from those 10 highest caloric items.

In [21]:
(
    dat2
    .sort(c.protein)
    .head(1)
)

shape: (1, 16)
┌────────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬────────────┬───────┐
│ item       ┆ food_group ┆ calories ┆ total_fat ┆ … ┆ vitamin_a ┆ vitamin_c ┆ wiki       ┆ color │
│ ---        ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---        ┆ ---   │
│ str        ┆ str        ┆ i64      ┆ f64       ┆   ┆ i64       ┆ i64       ┆ str        ┆ str   │
╞════════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪════════════╪═══════╡
│ Sour Cream ┆ dairy      ┆ 214      ┆ 20.9      ┆ … ┆ 13        ┆ 2         ┆ sour_cream ┆ white │
└────────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴────────────┴───────┘

7. Going back to the original dataset, filter just those rows where the amount of iron is more than 1mg (display **only**).

In [19]:
(
    dat
    .filter(c.iron > 1)
)

shape: (46, 16)
┌─────────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬────────────┬───────┐
│ item        ┆ food_group ┆ calories ┆ total_fat ┆ … ┆ vitamin_a ┆ vitamin_c ┆ wiki       ┆ color │
│ ---         ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---        ┆ ---   │
│ str         ┆ str        ┆ i64      ┆ f64       ┆   ┆ i64       ┆ i64       ┆ str        ┆ str   │
╞═════════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪════════════╪═══════╡
│ Asparagus   ┆ vegetable  ┆ 20       ┆ 0.1       ┆ … ┆ 15        ┆ 9         ┆ asparagus  ┆ green │
│ Avocado     ┆ fruit      ┆ 160      ┆ 14.6      ┆ … ┆ 3         ┆ 17        ┆ avocado    ┆ green │
│ Chickpea    ┆ grains     ┆ 180      ┆ 2.9       ┆ … ┆ 0         ┆ 3         ┆ chickpea   ┆ brown │
│ String Bean ┆ vegetable  ┆ 31       ┆ 0.1       ┆ … ┆ 14        ┆ 27        ┆ green_bean ┆ green │
│ Beef        ┆ meat       ┆ 288      ┆ 19.5      ┆ … ┆ 0         ┆ 0         ┆ beef       ┆ red   │
│ …           ┆ …          ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …          ┆ …     │
│ Swordfish   ┆ fish       ┆ 177      ┆ 8.2       ┆ … ┆ 5         ┆ 5         ┆ swordfish  ┆ white │
│ Tomato      ┆ vegetable  ┆ 18       ┆ 0.0       ┆ … ┆ 17        ┆ 21        ┆ tomato     ┆ red   │
│ Tuna        ┆ fish       ┆ 153      ┆ 3.9       ┆ … ┆ 3         ┆ 4         ┆ tuna       ┆ red   │
│ Turkey      ┆ meat       ┆ 187      ┆ 7.0       ┆ … ┆ 0         ┆ 0         ┆ turkey_(bi ┆ white │
│             ┆            ┆          ┆           ┆   ┆           ┆           ┆ rd)        ┆       │
│ Potato      ┆ vegetable  ┆ 104      ┆ 2.0       ┆ … ┆ 2         ┆ 12        ┆ potato     ┆ white │
└─────────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴────────────┴───────┘

8. Instead, now filter those rows where the amount of iron is more than or equal to 1mg (display only).

In [20]:
(
    dat
    .filter(c.iron >= 1)
)

shape: (58, 16)
┌───────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬─────────────┬────────┐
│ item      ┆ food_group ┆ calories ┆ total_fat ┆ … ┆ vitamin_a ┆ vitamin_c ┆ wiki        ┆ color  │
│ ---       ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---         ┆ ---    │
│ str       ┆ str        ┆ i64      ┆ f64       ┆   ┆ i64       ┆ i64       ┆ str         ┆ str    │
╞═══════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═════════════╪════════╡
│ Apple     ┆ fruit      ┆ 52       ┆ 0.1       ┆ … ┆ 1         ┆ 8         ┆ apple       ┆ red    │
│ Asparagus ┆ vegetable  ┆ 20       ┆ 0.1       ┆ … ┆ 15        ┆ 9         ┆ asparagus   ┆ green  │
│ Avocado   ┆ fruit      ┆ 160      ┆ 14.6      ┆ … ┆ 3         ┆ 17        ┆ avocado     ┆ green  │
│ Banana    ┆ fruit      ┆ 89       ┆ 0.3       ┆ … ┆ 1         ┆ 15        ┆ banana      ┆ yellow │
│ Chickpea  ┆ grains     ┆ 180      ┆ 2.9       ┆ … ┆ 0         ┆ 3         ┆ chickpea    ┆ brown  │
│ …         ┆ …          ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …           ┆ …      │
│ Tangerine ┆ fruit      ┆ 53       ┆ 0.3       ┆ … ┆ 14        ┆ 45        ┆ tangerine   ┆ orange │
│ Tomato    ┆ vegetable  ┆ 18       ┆ 0.0       ┆ … ┆ 17        ┆ 21        ┆ tomato      ┆ red    │
│ Tuna      ┆ fish       ┆ 153      ┆ 3.9       ┆ … ┆ 3         ┆ 4         ┆ tuna        ┆ red    │
│ Turkey    ┆ meat       ┆ 187      ┆ 7.0       ┆ … ┆ 0         ┆ 0         ┆ turkey_(bir ┆ white  │
│           ┆            ┆          ┆           ┆   ┆           ┆           ┆ d)          ┆        │
│ Potato    ┆ vegetable  ┆ 104      ┆ 2.0       ┆ … ┆ 2         ┆ 12        ┆ potato      ┆ white  │
└───────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴─────────────┴────────┘

9. Filter those rows where the food group is "fruit" and the iron is greater than 1. Make sure to use two different calls to the `.filter` function (display only).

In [23]:
(
    dat
    .filter((c.food_group == "fruit") & (c.iron > 1))
)

shape: (7, 16)
┌────────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬────────────┬────────┐
│ item       ┆ food_group ┆ calories ┆ total_fat ┆ … ┆ vitamin_a ┆ vitamin_c ┆ wiki       ┆ color  │
│ ---        ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---        ┆ ---    │
│ str        ┆ str        ┆ i64      ┆ f64       ┆   ┆ i64       ┆ i64       ┆ str        ┆ str    │
╞════════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪════════════╪════════╡
│ Avocado    ┆ fruit      ┆ 160      ┆ 14.6      ┆ … ┆ 3         ┆ 17        ┆ avocado    ┆ green  │
│ Grape      ┆ fruit      ┆ 69       ┆ 0.1       ┆ … ┆ 1         ┆ 18        ┆ grape      ┆ purple │
│ Kiwi       ┆ fruit      ┆ 61       ┆ 0.5       ┆ … ┆ 2         ┆ 155       ┆ kiwifruit  ┆ green  │
│ Lemon      ┆ fruit      ┆ 29       ┆ 0.0       ┆ … ┆ 0         ┆ 88        ┆ lemon      ┆ yellow │
│ Lime       ┆ fruit      ┆ 30       ┆ 0.0       ┆ … ┆ 1         ┆ 49        ┆ lime_(frui ┆ green  │
│            ┆            ┆          ┆           ┆   ┆           ┆           ┆ t)         ┆        │
│ Pineapple  ┆ fruit      ┆ 48       ┆ 0.1       ┆ … ┆ 1         ┆ 60        ┆ pineapple  ┆ yellow │
│ Strawberry ┆ fruit      ┆ 32       ┆ 0.0       ┆ … ┆ 0         ┆ 98        ┆ strawberry ┆ red    │
└────────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴────────────┴────────┘

10. Now repeat Q9 but this time use only one `.filter` function call making sure to use the correct operator (`|`, the or operator, or `&` the and operator; display only).

In [26]:
(
    dat
    .filter((c.food_group == "fruit") & (c.iron > 1))
)

shape: (7, 16)
┌────────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬────────────┬────────┐
│ item       ┆ food_group ┆ calories ┆ total_fat ┆ … ┆ vitamin_a ┆ vitamin_c ┆ wiki       ┆ color  │
│ ---        ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---        ┆ ---    │
│ str        ┆ str        ┆ i64      ┆ f64       ┆   ┆ i64       ┆ i64       ┆ str        ┆ str    │
╞════════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪════════════╪════════╡
│ Avocado    ┆ fruit      ┆ 160      ┆ 14.6      ┆ … ┆ 3         ┆ 17        ┆ avocado    ┆ green  │
│ Grape      ┆ fruit      ┆ 69       ┆ 0.1       ┆ … ┆ 1         ┆ 18        ┆ grape      ┆ purple │
│ Kiwi       ┆ fruit      ┆ 61       ┆ 0.5       ┆ … ┆ 2         ┆ 155       ┆ kiwifruit  ┆ green  │
│ Lemon      ┆ fruit      ┆ 29       ┆ 0.0       ┆ … ┆ 0         ┆ 88        ┆ lemon      ┆ yellow │
│ Lime       ┆ fruit      ┆ 30       ┆ 0.0       ┆ … ┆ 1         ┆ 49        ┆ lime_(frui ┆ green  │
│            ┆            ┆          ┆           ┆   ┆           ┆           ┆ t)         ┆        │
│ Pineapple  ┆ fruit      ┆ 48       ┆ 0.1       ┆ … ┆ 1         ┆ 60        ┆ pineapple  ┆ yellow │
│ Strawberry ┆ fruit      ┆ 32       ┆ 0.0       ┆ … ┆ 0         ┆ 98        ┆ strawberry ┆ red    │
└────────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴────────────┴────────┘

11. Continuing to repeat Q9, this time filter the rows where the food group is either "fruit" or "vegetable" again making sure to use the correct operator.

In [29]:
(
    dat
    .filter((c.food_group == "fruit") | (c.food_group == "vegetable"))
)

shape: (32, 16)
┌────────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬────────────┬────────┐
│ item       ┆ food_group ┆ calories ┆ total_fat ┆ … ┆ vitamin_a ┆ vitamin_c ┆ wiki       ┆ color  │
│ ---        ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---        ┆ ---    │
│ str        ┆ str        ┆ i64      ┆ f64       ┆   ┆ i64       ┆ i64       ┆ str        ┆ str    │
╞════════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪════════════╪════════╡
│ Apple      ┆ fruit      ┆ 52       ┆ 0.1       ┆ … ┆ 1         ┆ 8         ┆ apple      ┆ red    │
│ Asparagus  ┆ vegetable  ┆ 20       ┆ 0.1       ┆ … ┆ 15        ┆ 9         ┆ asparagus  ┆ green  │
│ Avocado    ┆ fruit      ┆ 160      ┆ 14.6      ┆ … ┆ 3         ┆ 17        ┆ avocado    ┆ green  │
│ Banana     ┆ fruit      ┆ 89       ┆ 0.3       ┆ … ┆ 1         ┆ 15        ┆ banana     ┆ yellow │
│ String     ┆ vegetable  ┆ 31       ┆ 0.1       ┆ … ┆ 14        ┆ 27        ┆ green_bean ┆ green  │
│ Bean       ┆            ┆          ┆           ┆   ┆           ┆           ┆            ┆        │
│ …          ┆ …          ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …          ┆ …      │
│ Strawberry ┆ fruit      ┆ 32       ┆ 0.0       ┆ … ┆ 0         ┆ 98        ┆ strawberry ┆ red    │
│ Sweet      ┆ vegetable  ┆ 86       ┆ 0.0       ┆ … ┆ 284       ┆ 4         ┆ sweet_pota ┆ orange │
│ Potato     ┆            ┆          ┆           ┆   ┆           ┆           ┆ to         ┆        │
│ Tangerine  ┆ fruit      ┆ 53       ┆ 0.3       ┆ … ┆ 14        ┆ 45        ┆ tangerine  ┆ orange │
│ Tomato     ┆ vegetable  ┆ 18       ┆ 0.0       ┆ … ┆ 17        ┆ 21        ┆ tomato     ┆ red    │
│ Potato     ┆ vegetable  ┆ 104      ┆ 2.0       ┆ … ┆ 2         ┆ 12        ┆ potato     ┆ white  │
└────────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴────────────┴────────┘

12. Can you provide the "definition" for what the `&` and `|` operators do fundamentally within Python (or coding in general)?

**Answer (Q12): **& is an "and" operator, while | is an "or" operator**

13. Finally, filter the rows that are fruits or vegetables using a different method; the `.is_in` function.

In [30]:
(
    dat
    .filter(c.food_group.is_in(["fruit", "vegetable"]))
)

shape: (32, 16)
┌────────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬────────────┬────────┐
│ item       ┆ food_group ┆ calories ┆ total_fat ┆ … ┆ vitamin_a ┆ vitamin_c ┆ wiki       ┆ color  │
│ ---        ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---        ┆ ---    │
│ str        ┆ str        ┆ i64      ┆ f64       ┆   ┆ i64       ┆ i64       ┆ str        ┆ str    │
╞════════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪════════════╪════════╡
│ Apple      ┆ fruit      ┆ 52       ┆ 0.1       ┆ … ┆ 1         ┆ 8         ┆ apple      ┆ red    │
│ Asparagus  ┆ vegetable  ┆ 20       ┆ 0.1       ┆ … ┆ 15        ┆ 9         ┆ asparagus  ┆ green  │
│ Avocado    ┆ fruit      ┆ 160      ┆ 14.6      ┆ … ┆ 3         ┆ 17        ┆ avocado    ┆ green  │
│ Banana     ┆ fruit      ┆ 89       ┆ 0.3       ┆ … ┆ 1         ┆ 15        ┆ banana     ┆ yellow │
│ String     ┆ vegetable  ┆ 31       ┆ 0.1       ┆ … ┆ 14        ┆ 27        ┆ green_bean ┆ green  │
│ Bean       ┆            ┆          ┆           ┆   ┆           ┆           ┆            ┆        │
│ …          ┆ …          ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …          ┆ …      │
│ Strawberry ┆ fruit      ┆ 32       ┆ 0.0       ┆ … ┆ 0         ┆ 98        ┆ strawberry ┆ red    │
│ Sweet      ┆ vegetable  ┆ 86       ┆ 0.0       ┆ … ┆ 284       ┆ 4         ┆ sweet_pota ┆ orange │
│ Potato     ┆            ┆          ┆           ┆   ┆           ┆           ┆ to         ┆        │
│ Tangerine  ┆ fruit      ┆ 53       ┆ 0.3       ┆ … ┆ 14        ┆ 45        ┆ tangerine  ┆ orange │
│ Tomato     ┆ vegetable  ┆ 18       ┆ 0.0       ┆ … ┆ 17        ┆ 21        ┆ tomato     ┆ red    │
│ Potato     ┆ vegetable  ┆ 104      ┆ 2.0       ┆ … ┆ 2         ┆ 12        ┆ potato     ┆ white  │
└────────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴────────────┴────────┘

13. Why do you think this is useful to use the `.is_in`?

**Answer (Q13):**

In [ ]:
#Sometimes we want to know whether a value belongs to a larger set.